export const ADD_ARTIST = "ADD_ARTIST";
export const REMOVE_ARTIST = "REMOVE_ARTIST";
export const ADD_GENRE = "ADD_GENRE";
export const REMOVE_GENRE = "REMOVE_GENRE";
export const ADD_POPULARITY_CHOICE = "ADD_POPULARITY_CHOICE";
export const REMOVE_POPULARITY_CHOICE = "REMOVE_POPULARITY_CHOICE";

