export const SET_GENRE_MOVIES = "SET_GENRE_MOVIES";
export const SET_ARTIST_MOVIES = "SET_ARTIST_MOVIES";
export const SET_PREFERENCE_MOVIES = "SET_PREFERENCE_MOVIES";
export const SET_RECOMMENDED_MOVIES = "SET_RECOMMENDED_MOVIES";


